version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/react/test/admin-frontend
hooks:
  BeforeInstall:
    - location: scripts/install-app.sh
      runas: root
  ApplicationStart:
    - location: scripts/start-app.sh
      timeout: 300
      runas: root